header:
  version: 8
machine: raspberrypi-cm3
distro: poky
target: iqrf-gatewayos-image
env:
  MENDER_ARTIFACT_NAME: 'release1'
  CI_PIPELINE_ID: 'pipelineID1'
repos:
  poky:
    url: "git://git.yoctoproject.org/poky"
    refspec: warrior
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:
  oe:
    url: "https://github.com/openembedded/meta-openembedded.git"
    refspec: warrior
    layers:
      meta-oe:
      meta-python:
      meta-networking:
      meta-multimedia:
      meta-webserver:
  raspberrypi:
    url: "https://github.com/agherzan/meta-raspberrypi.git"
    refspec: warrior
  mender:
    url: "https://github.com/mendersoftware/meta-mender.git"
    refspec: warrior
    layers:
      meta-mender-core:
      meta-mender-raspberrypi:
  meta-iqrf:
      layers:
        meta-iqrf:      
local_conf_header:
  custom: |
    IMAGE_FEATURES_append = " debug-tweaks"
    MACHINE_FEATURES_remove = "vc4graphics"
  rpi-specific: |
    ENABLE_SPI = "1"
    ENABLE_UART = "1"
    RPI_EXTRA_CONFIG = "dtoverlay=pi3-disable-bt"
  mender: |
    RPI_USE_U_BOOT = "1"
    IMAGE_ROOTFS_MAXSIZE = "1850000"
    MENDER_STORAGE_TOTAL_SIZE_MB = "3700"
    MENDER_PARTITION_ALIGNMENT = "4194304"
    MENDER_BOOT_PART_SIZE_MB = "128"
    MENDER_DATA_PART_SIZE_MB = "128"
    IMAGE_INSTALL_append = " kernel-image kernel-devicetree"
    IMAGE_FSTYPES_remove += " rpi-sdimg"
    MENDER_SERVER_URL = "https://mender.iqrf.org"
    MENDER_FEATURES_ENABLE_append = " mender-uboot mender-image mender-image-sd mender-install"
    MENDER_FEATURES_DISABLE_append = " mender-grub mender-image-uefi"
  systemd_enable: |
    DISTRO_FEATURES_append = " systemd"
    VIRTUAL-RUNTIME_init_manager = "systemd"
    DISTRO_FEATURES_BACKFILL_CONSIDERED = "sysvinit"
    VIRTUAL-RUNTIME_initscripts = ""
  distro: |
    DISTRO_FEATURES_remove = "irda pcmcia usbgadget nfs pci 3g nfc opengl ptest wayland vulkan pulseaudio x11"
